---
{{ $info := $.Values.name -}}
    {{ $dataFile := join "" (list "data/" $info ".yml") -}}
    {{ $data := .Files.Get $dataFile | fromYaml -}}
      {{ $fileJob := $data.fileJob -}}
      {{ $db := $data.config.db -}}
      {{ $es := $data.config.elastic_search -}}
      {{ $rb := $data.config.rabbitmq -}}
      {{ $api := $data.webApi -}}
      {{ $storage := $data.storage}}
    {{ $dataJson := toPrettyJson $api -}}
---
{{ if $api}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vn-suggestion
  namespace: {{$api.namespace}}
spec:

  selector:
    matchLabels:
      app: vn-suggestion
  replicas: 1
  #minimumReplicas: {{$api.replicas}}
  template:
    metadata:
      labels:
        app: vn-suggestion
    spec:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "xdoc"
          effect: "NoSchedule"
      containers:
        - image: docker.io/nttlong/vn-suggestion:amd.3
          name: vn-suggestion
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
 name: vn-suggestion
 namespace: {{$api.namespace}}
 labels:
   app: vn-suggestion
spec:
 type: NodePort
 selector:
   app: vn-suggestion
 ports:
   - name: "vn-suggestion-nod-port"
     protocol: TCP
     port: 8000
     targetPort: 8000
---
{{end}}
---