namespace: lv-file2
appConfig:
  name: lv-file2
  host:
    path: lvfile
    name: 172.16.7.99
    protocol: https
  ingress:
    pathType: Prefix
db:
  mongodb: mongodb://192.168.18.36:27017
  manage: 'lv-docs'
search:
  prefix_index: 'lv-codx'
  server: 'http://192.168.18.36:9200'
storage:
  server: 192.168.18.36
  directory: /codx-file-storage/files
  name: storage-files
replicas: 2
rabbit:
  username: guest
  password: guest
customer: "saas"
imageTag: "latest"
repository: "docker.lacviet.vn/xdoc"
#processMsg: ["content","google-file-sync","google-folder-sync","onedrive-file-sync"]
#processMsg_: ["re-do-all","content","image","index","google-file-sync","google-folder-sync","onedrive-file-sync"]
