{{ $images := .Files.Get "images.yml" | fromYaml -}}
{{ $jobsList:= fromYaml ((include "apps-data" (dict "values" .Values "images" $images) ))  -}}
{{- $check := $images.check_key }}
---
{{- range $key, $value := $jobsList.apps }}
---
{{ if $value.service }}
---
---
{{ if $value.service.ingress }}
  {{- $ip:= $value.service.ingress.ip }}
{{- $isNotUseIp:= (regexMatch $check $ip)}}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ $value.name }}-ingress
  namespace: {{ $value.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/rewrite-target: /{{$value.service.ingress.path}}/$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /{{$value.service.ingress.path}}/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{$value.name}}-service
                port:
                  number: 80

      {{ if $isNotUseIp }}
    host: {{$value.service.ingress.ip}}
      {{end}}
#      {{ if not $isNotUseIp }}
#status:
#  loadBalancer:
#    ingress:
#      - ip: {{$value.service.ingress.ip}}
#      {{end}}
---
{{end}}
{{end}}
{{- end}}