{{ $hasNodePort := and (hasKey .Values "nodePort") (hasKey (index .Values "nodePort") "tika") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  namespace: {{.Values.namespace}}
  #namespace: xdoc-web
spec:
  selector:
    matchLabels:
      app: tika
  replicas: {{.Values.libReplicas}}
  template:
    metadata:
      labels:
        app: tika
    spec:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "xdoc"
          effect: "NoSchedule"
      containers:
        - image: apache/tika:latest
          name: tika
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9998
---
apiVersion: v1
kind: Service
metadata:
 name: tika-service
 namespace: {{.Values.namespace}}
 labels:
   app: tika-service
spec:
  {{ if $hasNodePort }}
 type: NodePort
  {{ end }}
 selector:
   app: tika
 ports:
   - name: "tika-node-port"
     protocol: TCP
     port: 80
     targetPort: 9998
     {{ if $hasNodePort }}
     nodePort: {{ .Values.nodePort.tika }}
     {{ end }}
